#!/usr/bin/perl

while (<>) {
	chomp;
	push @lines, $_;
}

for ($i = 0; $i <= $#lines; $i++) {
	$_ = $lines[$i];

	if (/<td class="label_access_ctr"><strong>([^<]*)/) {
		push @id, $1;
	} elsif (/<td class="label_access_ctr">([^<]*)/) {
		$n = $1;
		$n =~ s/&nbsp;/ /g;
		$n =~ s/,//g;
		$n =~ s/ *$//;

		push @val, $n;
		$val{$id[$#val]} = $n;
	}
}

for ($i = 0; $i <= $#lines; $i++) {
	$_ = $lines[$i];

	if (/<div class="sm_text">([^<]*)/) {
		$direction = $1;
		@cols = ();
		$row = 0;
		$col = 0;
	}

	if (/<td class="sm_table_hdr" width="30" valign="bottom">([^<]*)/) {
		push @cols, $1;

		# print "col $1\n";
	}

	while (s/<td class="sm_cell" [^>]*nowrap>([^<]*)//) {
		$time[$row] = $1;

		if ($time[$row] =~ /^(\d+):(\d+) 00/ ||
		    $time[$row] =~ /^(\d+):(\d+) 13/) {
			$time[$row] = sprintf("%02d:%02d AM", $1, $2);
		}

		if ($time[$row] =~ /^(\d+):(\d+) (.)M/) {
			$hour = $1;
			$min = $2;
			if ($3 eq 'P' && $hour != 12) {
				$hour += 12;
			}

			$when = $hour * 60 + $min;
			$when2 = $when + 15;
			$time[$row] = sprintf("%02d:%02d - %02d:%02d", $when / 60, $when % 60, $when2 / 60, $when2 % 60);
		}
	}
	while (s/<td class="sm_cell"[^>]*>([^<]*)//) {
		# print "col $col\n";
		# print "count[$row]{$direction}{$cols[$col]} = $1;\n";

		$count[$row]{$direction}{$cols[$col++]} = $1;

	}
	if (/<tr>.*<\/tr/) {
		$row++;
		$col = 0;
	}

	last if /TRUCKS/;
}

print "id,name,id,date,time,";
for $direction ("SB", "WB", "NB", "EB") {
	for $turn ("Right", "Thru", "Left") {
		print "$direction-$turn,";
	}
}
for $direction ("SB", "WB", "NB", "EB") {
	for $turn ("Ped") {
		print "$direction-$turn,";
	}
}

print ",,,"; # should be bike counts
print "\n";

for ($i = 0; $i <= $#count; $i++) {
	$any = 0;
	for $direction ("SB", "WB", "NB", "EB") {
		for $turn ("Right", "Thru", "Left") {
			$any = 1 if $count[$i]{$direction}{$turn} > 0;
		}
	}
	for $direction ("SB", "WB", "NB", "EB") {
		$any = 1 if $count[$i]{$direction}{'Ped'} > 0;
	}
	next unless $any;

	print "$val{'INT ID'},";
	print "$val{'ROAD 1'}";

	for $x ('ROAD 2', 'ROAD 3', 'ROAD 4', 'COMMUNITY') {
		if ($val{$x} ne "") {
			print " / $val{$x}";
		}
	}

	print ",";
	print "$val{'INT ID'},";
	print "$val{'TMC DATE'},";

	print "$time[$i],";
	for $direction ("SB", "WB", "NB", "EB") {
		for $turn ("Right", "Thru", "Left") {
			# print "count[$row]{$direction}{$turn} ";
			print "$count[$i]{$direction}{$turn},";
		}
	}

	for $direction ("SB", "WB", "NB", "EB") {
		print "$count[$i]{$direction}{'Ped'},";
	}

	print ",,,"; # missing bike counts
	print "\n";
}
