#!/bin/sh

for i in buffalo dc minneapolis phoenix virginia-beach morpc
do
	echo $i
	find $i/report -name '*.html' -print | sort | xargs -L1 ./ms2soft/parse-report $i > counts-$i.csv
done

find hutrc -name '*.txt' -print | sort | tr '\012' '\0' | xargs -0 -L1 ./extract-ddot | (cd ../rtc-traffic-counts; ./extract-report-addresses) >> counts-dc.csv
