#!/usr/bin/perl

open(IN, "counts-minneapolis.csv");
while (<IN>) {
	chomp;
	($id, $name, $id2, $date, $time, @rest) = split(/,/);
	$walk = $rest[12] + $rest[13] + $rest[14] + $rest[15];

	$walk{"$name $date"}{$time} = $walk;
}

for $where (keys(%walk)) {
	%times = %{$walk{$where}};
	@times = keys(%times);
	$times = $#times + 1;

	next if $times != 96;

	for $t (@times) {
		$daytotal{$where} += $times{$t};
		$total{$t} += $times{$t};
		$total += $times{$t};
	}
}

for $where (keys(%daytotal)) {
	%times = %{$walk{$where}};
	@times = keys(%times);

	next if $daytotal{$where} == 0;

	if ($daytotal{$where} > $daytotal{$most}) {
		$most = $where;
	}

	for $t (@times) {
		if ($times{$t} != 0) {
			push @{$timelist{$t}}, ($daytotal{$where} / $times{$t});
		}
	}
}

for $t (sort(keys(%total))) {
	@l = sort { $a <=> $b } @{$timelist{$t}};

	$sum = 0;
	$count = 0;
	for ($i = $#l * 0; $i <= $#l * 1; $i++) {
		$sum += log($l[$i]);
		$count++;
	}
	$geom = exp($sum / $count);
	$scale{$t} = $geom;
	$median{$t} = $l[$#l / 2];
}

@daytotal = sort { $daytotal{$b} <=> $daytotal{$a} } keys(%daytotal);
@daytimes = sort(keys(%total));

for ($start = 0; $start <= $#daytimes; $start++) {
	print "$daytimes[$start] $scale{$daytimes[$start]} $median{$daytimes[$start]} ";
	for ($duration = 0; $duration <= 8 * 4; $duration++) {
	#for ($duration = 0; $duration <= $#daytimes; $duration++) {
		@deviations = ();

		for $d (@daytotal) {
			next if ($daytotal{$d} == 0);

			$sum = 0;
			$count = 0;

			for ($tt = $start; $tt < $start + $duration + 1; $tt++) {
				$t = $daytimes[$tt % ($#daytimes + 1)];

				if (1) { # $walk{$d}{$t} != 0) {
					$sum += $walk{$d}{$t} * $scale{$t};
					$count += 1;
				}
			}

			if ($count != 0 && $sum != 0) {
				push @deviations, log((($sum / $count)) / $daytotal{$d});

				# printf("%.6f %d\n", $sum / $count / $daytotal{$d}, $daytotal{$d});
			}
		}

		if ($#deviations < 0) {
			print "-- ";
			next;
		}

		$sum = 0;
		$count = 0;
		for $d (@deviations) {
			$sum += $d;
			$count++;
		}
		$mean = $sum / $count;
		$variance = 0;
		for $d (@deviations) {
			$variance += ($d - $mean) * ($d - $mean);
		}
		$variance /= $count;
		$stddev = sqrt($variance);
		printf("%.3f ", exp($stddev));
	}
	print "\n";
}
