#!/usr/bin/perl

for ($i = 2014; $i <= 2014; $i++) {
	system "curl -o hutrc/contractor-$i.html 'http://www.hutrc.howard.edu/Data/TMC_Contractor/search.php' -H 'Cookie: 007fb829ddbdd2a87668c06531fcc371=c04j3lsr0gtbc4orca5v4cs0d3' -H 'Origin: http://www.hutrc.howard.edu' -H 'Accept-Encoding: gzip,deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/38.0.2125.104 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://www.hutrc.howard.edu/Data/TMC_Contractor/search.php' -H 'Connection: keep-alive' --data 'DDOT_Archives_year=${i}&submit_update=Submit&streetA=&streetB=' --compressed";

	$text = "";
	open(IN, "hutrc/contractor-$i.html");
	while (<IN>) {
		$text .= $_;
	}
	close(IN);

	while ($text =~ s/href *= *'([^']*\.pdf)'//) {
		$url = $1;
		$url =~ s/ /%20/g;
		$url =~ s/,/%2C/g;
		$url = "http://www.hutrc.howard.edu/Data/TMC_Contractor/$url";

		$fname = $url;
		$fname =~ s/http:\/\///;

		$dir = $fname;
		$dir =~ s/\/[^\/]*$//;

		system "mkdir -p 'hutrc/$dir'";
		print "$url\n";
		system "curl -o 'hutrc/$fname' '$url'";
	}
	
}
