#!/usr/bin/perl

for ($i = 2011; $i <= 2013; $i++) {
	system "curl -o hutrc/contractor-$i.html 'http://www.hutrc.howard.edu/data/TMC_Contractor/search.php' -H 'Cookie: d949e3cd8d1fe760c0accdfe1a293b60=htirqmlt29lprc8pg0ed3dpph4; ja_ores_tpl=ja_ores' -H 'Origin: http://www.hutrc.howard.edu' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/35.0.1916.153 Safari/537.36' -H 'Content-Type: application/x-www-form-urlencoded' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Referer: http://www.hutrc.howard.edu/data/TMC_Contractor/search.php' -H 'Connection: keep-alive' --data 'DDOT_Archives_year=${i}&DDOT_Archives_month=Full_Year&submit_update=Submit' --compressed";

	$text = "";
	open(IN, "hutrc/contractor-$i.html");
	while (<IN>) {
		$text .= $_;
	}
	close(IN);

	while ($text =~ s/href *= *'([^']*\.pdf)'//) {
		$url = $1;
		$url =~ s/ /%20/g;
		$url = "http://www.hutrc.howard.edu/data/TMC_Contractor/$url";

		$fname = $url;
		$fname =~ s/http:\/\///;

		$dir = $fname;
		$dir =~ s/\/[^\/]*$//;

		system "mkdir -p 'hutrc/$dir'";
		system "curl -o 'hutrc/$fname' '$url'";
	}
	
}
