#!/usr/bin/perl

for ($i = 1; $i < 71; $i++) {
	print "\n$i\n";

	system "curl -o 'index/$i.html' 'http://dc.ms2soft.com/tcds/tmcdata.asp?offset=&id=$i&a=193' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Connection: keep-alive' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Cookie: __utma=233346690.1708018771.1395988809.1395988809.1395988809.1; __utmc=233346690; __utmz=233346690.1395988809.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); ASPSESSIONIDCAAACSTD=HEHOPCECJHPDOBMHOPHFNIAG; ASP.NET_SessionId=rb2aazoppu1q0ydrsm5xo1cv; __utma=1.1992255864.1396029913.1396029913.1396029913.1; __utmb=1.56.10.1396029913; __utmc=1; __utmz=1.1396029913.1.1.utmcsr=gbnrtc.org|utmccn=(referral)|utmcmd=referral|utmcct=/index.php/resources/data/traffic-count-database-system/' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36' --compressed";

	open(IN, "index/$i.html");
	while (<IN>) {
		if (/href="(rpt_tmc-cars_and_trucks.asp?[^"]*)"/) {
			$url = $1;

			system "curl -o 'report/$i.html' 'http://dc.ms2soft.com/tcds/$url' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://dc.ms2soft.com/tcds/tmcdata.asp?offset=9&id=10&a=193' -H 'Cookie: __utma=233346690.1708018771.1395988809.1396034178.1396036089.3; __utmb=233346690.1.10.1396036089; __utmc=233346690; __utmz=233346690.1395988809.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); ASPSESSIONIDCAAACSTD=CEIOPCECGPKLDBOEAPAIPLPG; ASP.NET_SessionId=1oklbq23mc4hnao53am330bp; __utma=1.1611933542.1396036289.1396036289.1396036289.1; __utmb=1.19.10.1396036289; __utmc=1; __utmz=1.1396036289.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --compressed";
		}
	}
}
