#!/usr/bin/perl

mkdir "index";
mkdir "report";

for ($i = 1; $i < 6575; $i++) {
	print "\n$i\n";

	system "curl -o 'index/$i.html' 'http://morpc.ms2soft.com/tcds/tmcdata.asp?offset=&id=$i&a=23' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://morpc.ms2soft.com/tcds/tdetail_tmc.asp?offset=10&sort_fld=INTID&sort_dir=ASC' -H 'Cookie: __utma=233346690.1708018771.1395988809.1396120149.1399763283.5; __utmc=233346690; __utmz=233346690.1395988809.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); ASPSESSIONIDQCDCASRA=BJFIGKKBDHLCCGOPIFBCOBII; ASP.NET_SessionId=ozmjzxcyvoaklrztw5diupj2; __utma=1.1134292908.1401216519.1401216519.1401216519.1; __utmb=1.38.10.1401216519; __utmc=1; __utmz=1.1401216519.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --compressed";

	open(IN, "index/$i.html");
	while (<IN>) {
		if (/href="(rpt_tmc-cars_and_trucks.asp?[^"]*)"/) {
			$url = $1;

			system "curl -o 'report/$i.html' 'http://morpc.ms2soft.com/tcds/$url' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://morpc.ms2soft.com/tcds/tmcdata.asp?offset=10&id=40&a=23' -H 'Cookie: __utma=233346690.1708018771.1395988809.1396120149.1399763283.5; __utmc=233346690; __utmz=233346690.1395988809.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); ASPSESSIONIDQCDCASRA=BJFIGKKBDHLCCGOPIFBCOBII; ASP.NET_SessionId=ozmjzxcyvoaklrztw5diupj2; __utma=1.1134292908.1401216519.1401216519.1401216519.1; __utmb=1.40.10.1401216519; __utmc=1; __utmz=1.1401216519.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --compressed";
		}
	}
}
