#!/usr/bin/perl

while (<>) {
	($id, $name, $id2, $date, $time, @fields) = split(/,/);

	if ($time =~ /(..):(..) *- *(..):(..)/) {
		$time = $1 + $2 / 60;
	}

        $walk = $fields[12] + $fields[13] + $fields[14] + $fields[15];
	$walk{$name}{$time} = $walk;

	for ($i = 0; $i < 12; $i++) {
		$drive{$name}{$time} += $fields[$i];
	}
}

for $name (keys(%walk)) {
	if ($walk{$name}{0} ne "") {
		@l = keys(%{$walk{$name}});
		next unless $#l == 95;

		for $time (keys(%{$walk{$name}})) {
			$sum{$time} += $walk{$name}{$time};
			$drivesum{$time} += $drive{$name}{$time};
		}
	}
}

for $time (sort {$a <=> $b} (keys(%sum))) {
	print "$time $sum{$time} $drivesum{$time}\n";
}
