#!/usr/bin/perl

$city = "dc";

# minneapolis.ms2soft.com
# enable developer tools
# TMC
# from, to, SEARCH
# List View
# 1
# TMC
# find the tmcdata.asp?... URL

$index = "curl 'http://dc.ms2soft.com/tcds/tmcdata.asp?offset=0&id=1&a=193&diag=1' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.124 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://dc.ms2soft.com/tcds/tdetail_tmc.asp?offset=0&sort_fld=INTID&sort_dir=ASC' -H 'Cookie: ASPSESSIONIDCAABBDAB=EHPLMLACEEPMCIAFJDAJCNLF; __utmt=1; ASP.NET_SessionId=434bqrd1z22dqztioihftnww; ASPSESSIONIDACADACBA=LHHLLLLBHMMIPJICHGHHHHNL; __utma=1.1147855793.1435795119.1435795119.1435795119.1; __utmb=1.58.10.1435795119; __utmc=1; __utmz=1.1435795119.1.1.utmcsr=hutrc.howard.edu|utmccn=(referral)|utmcmd=referral|utmcct=/' -H 'Connection: keep-alive' --compressed";

$index =~ s/^curl //;

mkdir "index";
mkdir "report";
mkdir "report-bikes";

for ($i = 1; $i < 94; $i++) {
	print "\n$i\n";

	$index =~ s/id=[0-9]+/id=$i/;
	system "curl -o index/$i.html $index";

	$rest = $index;
	$rest =~ s/'http[^']*' //;

	$vehicle = "";
	$combined = "";
	$bikes = "";

	open(IN, "index/$i.html");
	while (<IN>) {
		if (/href="(rpt_tmc-cars_and_trucks.asp?[^"]*)"/) {
			$vehicle = $1;
		}

		if (/href="(rpt_tmc-cars-trucks.asp?[^"]*)"/) {
			$combined = $1;
		}

		if (/href="(rpt_tmc-bikes.asp?[^"]*)"/) {
			$bikes= $1;
		}
	}

	if ($vehicle ne "") {
		system "curl -o 'report/$i.html' 'http://$city.ms2soft.com/tcds/$vehicle' $rest";
	} elsif ($combined ne "") {
		system "curl -o 'report/$i.html' 'http://$city.ms2soft.com/tcds/$combined' $rest";
	}

	if ($bikes ne "") {
		system "curl -o 'report-bikes/$i.html' 'http://$city.ms2soft.com/tcds/$bikes' $rest";
	}
}
