#!/usr/bin/perl

sub out {
	return if $_[1] == 0 && $_[2] == 0;
	printf(@_);
}

#              12
#              
#            0 1 2
#         11        3
#  15     10        4    13
#         9         5
#            6 7 8
#
#              14

while (<>) {
	chomp;

	($id1, $name, $id2, $date, $time, @rest) = split(/,/);

	# North crosswalk
	out("%d %d %d %s\n", $rest[12], $rest[3] + $rest[11], $rest[1], "$id1 $name");
	# East crosswalk
	out("%d %d %d %s\n", $rest[13], $rest[2] + $rest[6], $rest[4], "$id1 $name");
	# South crosswalk
	out("%d %d %d %s\n", $rest[14], $rest[5] + $rest[9], $rest[7], "$id1 $name");
	# West crosswalk
	out("%d %d %d %s\n", $rest[15], $rest[0] + $rest[8], $rest[10], "$id1 $name");
}
