#!/usr/bin/perl

for ($i = 1; $i < 1000; $i++) {
	print "\n$i\n";
	# system "curl -o index/$i.html 'http://minneapolis.ms2soft.com/tcds/tmcdata.asp?offset=&id=$i&a=40' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Cache-Control: max-age=0' -H 'Cookie: ASPSESSIONIDCAAACSTD=IPAOPCECAGFDJIOMJCFMHKOB; ASP.NET_SessionId=y5gohqfm43njtym5ikjl0yqn; __utma=233346690.1708018771.1395988809.1395988809.1395988809.1; __utmb=233346690.5.10.1395988809; __utmc=233346690; __utmz=233346690.1395988809.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=1.765693387.1395988308.1395988308.1395988308.1; __utmb=1.114.10.1395988308; __utmc=1; __utmz=1.1395988308.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' -H 'Connection: keep-alive' --compressed";

	open(IN, "index/$i.html");
	while (<IN>) {
		if (/href="(rpt_tmc-cars_and_trucks.asp?[^"]*)"/) {
			$url = $1;

			system "curl -o 'report/$i.html' 'http://minneapolis.ms2soft.com/tcds/$url' -H 'Accept-Encoding: gzip,deflate,sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_8_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36' -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8' -H 'Referer: http://minneapolis.ms2soft.com/tcds/tmcdata.asp?offset=&id=986&a=40' -H 'Cookie: ASPSESSIONIDCAAACSTD=IPAOPCECAGFDJIOMJCFMHKOB; ASP.NET_SessionId=y5gohqfm43njtym5ikjl0yqn; __utma=233346690.1708018771.1395988809.1395988809.1395988809.1; __utmc=233346690; __utmz=233346690.1395988809.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none); __utma=1.765693387.1395988308.1395988308.1396026345.2; __utmb=1.49.10.1396026345; __utmc=1; __utmz=1.1395988308.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)' -H 'Connection: keep-alive' -H 'Cache-Control: max-age=0' --compressed"
		}
	}
}
